### ISSUE TITLE
Crashed during loading

### ISSUE THREAD

**Issue by horstefan** [gruijter/com.gruijter.facepp#1]
no further info available. 
fresh install. no configuration yet (also not possible without starting the app)

installed apps:
![image](https://user-images.githubusercontent.com/23259607/80573926-2d6dea80-8a01-11ea-9c36-46542bdb0f3b.png)

![image](https://user-images.githubusercontent.com/23259607/80573899-25ae4600-8a01-11ea-8f89-4df2616a55ee.png)

**Comment by horstefan** [comment]
![Screenshot_20200429_101730_app homey](https://user-images.githubusercontent.com/23259607/80574852-e4b73100-8a02-11ea-8923-5d07284f7a01.jpg)

**Comment by gruijter** [comment]
Temporary fix: from the app folder do `npm i fixture-stdout`

**Comment by horstefan** [comment]
confirmed working. Thanks will start playing now ;)
