### ISSUE TITLE
Flow not triggered with unknown faces

### ISSUE THREAD

**Issue by KRiZ-R** [gruijter/com.gruijter.facepp#10]
Hi, this app is great!
It seems that the flow is not triggered when it finds an unknown face.
They do show up in the log.

**Comment by gruijter** [comment]
Thx for reporting.

If you restart the app, does it work again then?

**Comment by gruijter** [comment]
I think I found it. It is not an issue in the FACE++ app itself. When I try to send NO_MATCH (with underscore) to telegram, it doesn't get send. I will change it to NOMATCH so that it does work.

Did you also use telegram, or some other service?

**Comment by KRiZ-R** [comment]
I think you are right!
I am using telegram. I just tested sending NO_MATCH and NOMATCH to telegram, but only NOMATCH was sent.

**Comment by gruijter** [comment]
fixed in 1.1.6

**Comment by KRiZ-R** [comment]
Thank you, it works!
I donated yesterday!

**Comment by gruijter** [comment]
Ah so that was you. Thx and cheers 😘🍻
