### ISSUE TITLE
Request: Flow when image is processed

### ISSUE THREAD

**Issue by horstefan** [gruijter/com.gruijter.facepp#2]
Can you add it so every processed image generates a flow?
Even without a programmed face it should be able to detect age, gender etc

or should i just set the threshold to 0 and let homey figure it out?

**Comment by gruijter** [comment]
What you describe should already work. All faces that are detected will trigger a flow, even if not trained in settings. However, when no face detected it will not trigger a flow. This happens when a face is too small in the snapshot (less then around 75px wide). You see a log when this happens.

**Comment by horstefan** [comment]
Allright. the confidence setting made me believe otherwise. thank you for the explanation.
