### ISSUE TITLE
Auto-add unknown faces to face set

### ISSUE THREAD

**Issue by sossienl** [gruijter/com.gruijter.facepp#4]
I love this app, I had built my own setup via a 3rd party PHP server, which I can probably dismiss now.

Question; 
Can I get the metadata if there is a face found, but just not a known face? 
Also, can I add these unknown faces?

Usecase: Camera detects someone in the front garden, Face++ will analyze the image, finds a face but it cannot identify it. I still would like to get the information it has about the face/person.

Also adding unknown faces would be easier than adding them manually

**Comment by gruijter** [comment]
Adding unknown faces is a usecase on my roadmap list already. But it requires image manipulation by Homey (cut the face from the entire image). So it is not a minor thing to do. I am working on stability first before trying to add this function.

Metadata of unknown faces is already implemented. The face-found flow is triggered with all the metadata with label NO_MATCH and confidence 0. It is also logged in the settings log. At least, that is what is supposed to happen. Please let me know if not the case.

**Comment by sossienl** [comment]
Ah understood. Is that not something that faceplusplus.com can facilitate? I do understand that it's a more complex thing for Homey to solve.

My flow is not triggered in the case of "NO_MATCH" even though I do see the results in the log.
and in the case of "No Faces found in the image" also nothing is happening.

**Comment by sossienl** [comment]
I do see a token generated for unknown faces btw. Even to refer to that token to define a new face would be a shortcut

**Comment by gruijter** [comment]
I will check why unknown faces do not trigger the flow.

Yes the face token is produced, but to make it user friendly I want the face image to be shown in the settings page. If multiple persons are in an image, you will get multiple face tokens.

With 'no faces found' there is no metadata to work with at all.

**Comment by gruijter** [comment]
> I will check why unknown faces do not trigger the flow.

I checked, but it works fine here. In the next release I will add a test image to make testing this possible without need for a camera snaphot.

**Comment by gruijter** [comment]
I decided I will not implement auto-adding unknown faces. It will pollute the database too much. I implemented face snapshot that is available as a token in flows. With that face snapshot you can manually add new unknown faces.
